version: "3.4"

services:
  nginx:
    container_name: nginx
    image: npm_nginx:latest 
    build:
      context: ./nginx
      args:
        - DOMAIN=domain.com
        - NPM_PORT=4873
        - DOCKER_PORT=5000
      dockerfile: ./nginx.dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
    networks:
      - registry-network
    logging:
      driver: "json-file"
      options:
        max-size: "1000k"
        max-file: "3"

  npmregistry:
    container_name: npm
    image: npm_registry:latest 
    build:
      context: ./verdaccio
      dockerfile: ./verdaccio.dockerfile
    ports:
      - 4873:4873
    volumes:
      - ./verdaccio/conf:/verdaccio/conf
      - ./verdaccio/storage:/verdaccio/storage:z
    networks:
      - registry-network
    logging:
      driver: "json-file"
      options:
        max-size: "1000k"
        max-file: "3"

  dockerregistry:
    container_name: docker
    image: registry:2
    ports:
      - 127.0.0.1:5000:5000
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./data:/data
    networks:
      - registry-network
    logging:
      driver: "json-file"
      options:
        max-size: "1000k"
        max-file: "3"

volumes:
  registry:
    driver: local

networks:
  registry-network:
    driver: bridge

